/*
50-CUANTOS DIAS DE VACACIONES CORRESPONDIERON A CADA EMPLEADO 
EL PRIMER AÑO DE TRABAJO (CONTANDO 1 POR DIA POR SEMANA ENTERA 
TRABAJADA
*/
SELECT ENAME,HIREDATE, TO_CHAR(HIREDATE,'YYYY'), '3112'||TO_CHAR(HIREDATE,'YYYY'),
        TO_DATE('3112'||TO_CHAR(HIREDATE,'YYYY'),'DDMMYYYY'),
        TO_DATE('3112'||TO_CHAR(HIREDATE,'YYYY'),'DDMMYYYY')-HIREDATE AS DIAS_CONTRATADOS,
        TRUNC((TO_DATE('3112'||TO_CHAR(HIREDATE,'YYYY'),'DDMMYYYY')-HIREDATE)/7) AS SEMANA
FROM EMP
WHERE HIREDATE IS NOT NULL;

SELECT ENAME,HIREDATE, TO_CHAR(HIREDATE,'YYYY'), '3112'||TO_CHAR(HIREDATE,'YYYY'),
        TO_DATE('3112'||TO_CHAR(HIREDATE,'YYYY'),'DDMMYYYY'),
        TO_DATE('3112'||TO_CHAR(HIREDATE,'YYYY'),'DDMMYYYY')-HIREDATE AS DIAS_CONTRATADOS,
        TRUNC((TO_DATE('3112'||TO_CHAR(HIREDATE,'YYYY'),'DDMMYYYY')-HIREDATE)/7) AS SEMANA
FROM EMP
WHERE HIREDATE IS NOT NULL;
