DROP TABLE ALUMNOS;

CREATE TABLE ALUMNOS
(CODIGO INTEGER PRIMARY KEY,
NOMBRE VARCHAR2(20) NOT NULL,
APELLIDOS VARCHAR2(50) NOT NULL,
FECNAC DATE,
CURSO VARCHAR2(10),
SEXO CHAR(1),
EDAD INTEGER);

INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (1,'FRANCISCA MARIA','PEREZ URENA','01/01/2000','2DAM','M',20);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (2,'JAIME','MARTIN BASTOS','12/10/1999','2DAM','H',21);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (3,'LUIS CARLOS','PIMENTEL TORRES','30/08/2000','2DAM','H',20);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (4,'MARIO','CAPACETE VELASCO','09/06/2001','1DAM','H',19);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (5,'ANGEL','DIAZ DEL RIO YANGUAS','13/04/2000','1DAM','H',20);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (6,'NYDIA','LOPEZ MONTERO','10/06/2000','1DAM','M',20);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (7,'MARIA','LEON PEREZ','25/02/2002','1DAM','M',18);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (8,'JAIME','GARCIA MOLINA','26/06/1999','1DAM','H',21);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (9,'JESUS','CORTAZAR ROMERA','10/09/1998','1DAM','H',22);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (10,'ALVARO', 'BULNES RAMOS','11/06/1999','2DAM','H',20);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (11,'CESAR', 'CONCEPCION CAMILO','28/10/2000','2DAM','H',19);

INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (12,'ANDRES','CABANAS PECHERO','25/08/2002','1DAM','H',18);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (13,'JOSE MANUEL','CANAL LARA','03/09/1999','1DAM','H',21);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (14,'FRANCISCO JOSE','DIAZ
BAUTISTA','06/09/1989','1DAM','H',31);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (15,'MANUEL','GAMIZ REY','10/01/1999','1DAM','H',21);

INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (16,'CARLOS','MARTINEZ BARON','27/07/2000','1DAM','H',20);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (17,'DAVID','MARTINEZ MERENCIO','01/10/2002','1DAM','H',18);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (18,'IVAN','MATIAS DEL SOLAR','13/11/2001','1DAM','H',18);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (19,'TOMAS','MILLAN SANCHEZ','07/03/2000','1DAM','H',20);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (20,'MANUEL','OLIVA TORRES','26/12/1999','1DAM','H',20);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (21,'JUAN PABLO','PALOMARES AVILA','21/11/1986','1DAM','H',33);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (22,'JESUS','PEREZ CAMPILLO','15/03/1979','1DAM','H',41);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (23,'EUGENIO','PEREZ JIMENEZ','13/04/1978','1DAM','H',42);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (24,'IGNACIO','POLAINA GOMEZ','13/02/1999','1DAM','H',21);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (25,'JUAN MARIA','POLEY BORGES','29/10/2002','1DAM','H',17);

INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (26,'MIGUEL ANGEL','RODRIGUEZ
DALI','28/08/1999','1DAM','H',21);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (27,'JOSE RAMON','ROMERO VALENCIA','18/09/1996','1DAM','H',24);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (28,'JAVIER ANDRES','SALGUERO
PEREZ','23/11/1991','1DAM','H',28);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (29,'MIHAI AURELIAN','STANCIU','12/02/1999','2DAM','H',21);
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,
EDAD)
VALUES (30,'ANTONIO','BUENO GUISADO',NULL,'PROF','H',NULL);

INSERT INTO ALUMNOS
    (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO,SEXO, EDAD)
VALUES
    (101,'ADRIAN','BORREGO PIRES',TO_DATE('15/05/2000','DD/MM/YYYY'), '1DAW','H',22);

INSERT INTO ALUMNOS
    (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO,SEXO, EDAD)
VALUES
    ((SELECT MAX(CODIGO)+1 FROM ALUMNOS),'ELVIS FABRICIO','ZHUNE MERO',TO_DATE('28/12/1996','DD/MM/YYYY'), '1DAW','H',25);
    
    INSERT INTO ALUMNOS
    (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO,SEXO, EDAD)
VALUES
    ((SELECT MAX(CODIGO)+1 FROM ALUMNOS),'DERIAN YERAY','BATALLAS MINDA',TO_DATE('12/07/2002','DD/MM/YYYY'), '1DAW','H',20);

INSERT INTO ALUMNOS
    (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO,SEXO, EDAD)
VALUES
    ((SELECT MAX(CODIGO)+1 FROM ALUMNOS),'IRENE','SANCHEZ RUANO',TO_DATE('27/04/1992','DD/MM/YYYY'), '1DAW','M',30);

INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO,EDAD)
VALUES ((SELECT MAX(CODIGO)+1 FROM ALUMNOS),'IVAN','GUERRA SALAS',TO_DATE('05/09/2000','DD/MM/YYYY'),'1DAW','H',22);

INSERT INTO ALUMNOS
    (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO,SEXO, EDAD)
VALUES
    ((SELECT MAX(CODIGO)+1 FROM ALUMNOS),'FRANCISCO','RIVERA GIL',TO_DATE('23/02/2004','DD/MM/YYYY'), '1DAW','H',18);

INSERT INTO ALUMNOS
    (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO, EDAD)
VALUES
    ((SELECT MAX(CODIGO)+1 FROM ALUMNOS),'ALBERTO','CARO BARRERA',TO_DATE('05/02/1994','DD/MM/YYYY'),'1DAW','H',28);

INSERT INTO ALUMNOS
    (CODIGO, NOMBRE, APELLIDOS, FECNAC, CURSO, SEXO,EDAD)
VALUES
    ((SELECT MAX(CODIGO)+1 FROM ALUMNOS), 'LUIS', 'VAZQUEZ FRANCO', TO_DATE('06/03/1994', 'DD/MM/YYYY'),'1DAW','H',28);

INSERT INTO ALUMNOS
    (CODIGO, NOMBRE, APELLIDOS,FECNAC, CURSO, SEXO, EDAD)
VALUES
    ((SELECT MAX(CODIGO)+1 FROM ALUMNOS),'RAFAEL','CAMPOS PEREA',TO_DATE('03/05/2000','DD/MM/YYYY'),'1DAW','H',22);

INSERT INTO ALUMNOS
    (CODIGO,NOMBRE,APELLIDOS,FECNAC, CURSO,SEXO, EDAD)
VALUES
    ((SELECT MAX(CODIGO)+1 FROM ALUMNOS),'ALVARO','RODRIGUEZ GARRIDO', TO_DATE('26/03/1999','DD/MM/YYYY'),'1DAW','H',23);

INSERT INTO ALUMNOS
    (CODIGO, NOMBRE, APELLIDOS,FECNAC,CURSO,SEXO,EDAD)
VALUES
    ((SELECT MAX(CODIGO)+1 FROM ALUMNOS),'ALEJANDRO','GOMEZ RIVERA',TO_DATE('15/10/2002','DD/MM/YYYY'), '1DAW','H',20);
    
INSERT INTO ALUMNOS (CODIGO, NOMBRE, APELLIDOS, FECNAC, CURSO, SEXO, EDAD)
VALUES ((SELECT MAX(CODIGO)+1 FROM ALUMNOS), 'nelson ramon', 'galicia carrero', TO_DATE('20/08/1993','DD/MM/YYYY'),'1daw', 'h',29);


commit;