DROP TABLE MONTANIA;
DROP TABLE LAGO;
DROP TABLE RIO;
DROP TABLE HAY;
DROP TABLE ACCIDENTE_GEOGRAFICO;
DROP TABLE PAIS;

CREATE TABLE PAIS (
    COD_PAIS INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(10),
    LOCALIDAD VARCHAR2(10),
    EXTENSION NUMBER(4,5),
    POBLACION INTEGER 
);

CREATE TABLE ACCIDENTE_GEOGRAFICO (
    COD_ACCIDENTE_GEOGRAFICO INTEGER NOT NULL PRIMARY KEY,
    TIPO_ACCIDENTE_GEOGRAFICO VARCHAR2(10)
);

CREATE TABLE HAY (
    COD_PAIS INTEGER NOT NULL PRIMARY KEY,
    COD_ACCIDENTE_GEOGRAFICO INTEGER 
);

CREATE TABLE RIO(
    COD_RIO INTEGER NOT NULL PRIMARY KEY,
    COD_ACCIDENTE_GEOGRAFICO INTEGER,
    POSICION_VERTICAL NUMBER(4,5),
    LOCALIDAD VARCHAR2(10),
    LONGITUD NUMBER(4,5),
    POSICION_HORIZONTAL NUMBER(4,5),
    NOMBRE VARCHAR2(10)
);

CREATE TABLE LAGO(
    COD_LAGO INTEGER NOT NULL PRIMARY KEY,
    COD_ACCIDENTE_GEOGRAFICO INTEGER,
    POSICION_VERTICAL NUMBER(4,5),
    EXTENSION NUMBER(4,5),
    POSICION_HORIZONTAL NUMBER(4,5),
    NOMBRE VARCHAR2(10)
);

CREATE TABLE MONTANIA(
    COD_MONTANIA INTEGER NOT NULL PRIMARY KEY,
    COD_ACCIDENTE_GEOGRAFICO INTEGER,
    POSICION_VERTICAL NUMBER(4,5),
    ALTURA NUMBER(4,5),
    POSICION_HORIZONTAL NUMBER(4,5),
    NOMBRE VARCHAR2(10)
);

/*ALTERS*/
ALTER TABLE HAY 
ADD CONSTRAINT FK_COD_PAIS_PAIS
FOREIGN KEY (COD_PAIS)
REFERENCES PAIS(COD_PAIS);

ALTER TABLE HAY 
ADD CONSTRAINT FK_COD_ACCIDENTE_GEOGRAFICO
FOREIGN KEY  (COD_ACCIDENTE_GEOGRAFICO)
REFERENCES ACCIDENTE_GEOGRAFICO(COD_ACCIDENTE_GEOGRAFICO);

ALTER TABLE RIO 
ADD CONSTRAINT FK_COD_ACCIDENTE_GEOGRAFICO_RIO
FOREIGN KEY (COD_ACCIDENTE_GEOGRAFICO)
REFERENCES ACCIDENTE_GEOGRAFICO(COD_ACCIDENTE_GEOGRAFICO);

ALTER TABLE LAGO 
ADD CONSTRAINT FK_COD_ACCIDENTE_GEOFRAFICO_LAGO 
FOREIGN KEY (COD_ACCIDENTE_GEOGRAFICO)
REFERENCES ACCIDENTE_GEOGRAFICO(COD_ACCIDENTE_GEOGRAFICO);

ALTER TABLE MONTANIA
ADD CONSTRAINT FK_COD_ACCIDENTE_GEOGRAFICO_MONTANIA
FOREIGN KEY (COD_ACCIDENTE_GEOGRAFICO)
REFERENCES ACCIDENTE_GEOGRAFICO(COD_ACCIDENTE_GEOGRAFICO);