DROP TABLE REL_AUTORES_ARTICULOS;
DROP TABLE REL_TIPOAUTOR_AUTORES;
DROP TABLE TIPOS_AUTOR;
DROP TABLE AUTORES;
DROP TABLE PELICULA;
DROP TABLE LIBRO;
DROP TABLE CD;
DROP TABLE ARTICULOS;
DROP TABLE TIPOS_ARTICULO;
DROP TABLE PRESTAMOS;
DROP TABLE SOCIO_TELEFONOS;
DROP TABLE SOCIOS;


CREATE TABLE SOCIOS (
    CODSOCIO INTEGER NOT NULL PRIMARY KEY,
    DNI CHAR(9),
    NOMBRE VARCHAR2(20),
    APELLIDOS VARCHAR2(50),
    DIRECCION VARCHAR2(50)
);

CREATE TABLE SOCIO_TELEFONOS (
    NUMTELEFONO VARCHAR2(30) NOT NULL PRIMARY KEY,
    CODSOCIO INTEGER
);


CREATE TABLE PRESTAMOS(
    FECHA_PRESTAMO DATE NOT NULL PRIMARY KEY,
    CODSOCIO INTEGER,
    CODARTICULO VARCHAR2(20),
    FECHA_TOPE DATE,
    FECHA_ENTREGA DATE 
);

CREATE TABLE TIPOS_ARTICULO(
    CODTIPO INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(10)
);

CREATE TABLE ARTICULOS (
    CODARTICULO VARCHAR2(20) NOT NULL PRIMARY KEY,
    CODTIPO INTEGER,
    NOMBRE VARCHAR2(20),
    ANHO_CREACION INTEGER,
    RESUMEN VARCHAR(4000),
    DETERIORO CHAR(1),
    DESCRIPCION_DETERIORO VARCHAR2(500)
);

CREATE TABLE CD (
    CODARTICULO VARCHAR2(20) NOT NULL PRIMARY KEY,
    NUMCANCIONES INTEGER
);

CREATE TABLE LIBRO (
    CODARTICULO VARCHAR2(20) NOT NULL PRIMARY KEY,
    NUM_PAGINAS INTEGER
);

CREATE TABLE PELICULA (
    CODARTICULO VARCHAR2(20) NOT NULL PRIMARY KEY,
    DURACION INTEGER
);

CREATE TABLE AUTORES (
    CODAUTOR INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    PAIS VARCHAR2(20)
);

CREATE TABLE TIPOS_AUTOR(
    CODTIPOAUTOR INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(20)
);

CREATE TABLE REL_TIPOAUTOR_AUTORES (
    CODAUTOR INTEGER PRIMARY KEY NOT NULL,
    CODTIPOAUTOR INTEGER
);

CREATE TABLE REL_AUTORES_ARTICULOS (
    CODAUTOR INTEGER NOT NULL PRIMARY KEY, 
    CODTIPOAUTOR INTEGER,
    CODARTICULO VARCHAR2(20)
);


/*ALTER TABLES*/
ALTER TABLE SOCIO_TELEFONOS
ADD CONSTRAINT FK_CODSOCIO_SOCIOS
FOREIGN KEY (CODSOCIO)
REFERENCES SOCIOS(CODSOCIO);

ALTER TABLE PRESTAMOS 
ADD CONSTRAINT FK_CODSOCIO_SOCIOS_PRESTAMOS
FOREIGN KEY (CODSOCIO)
REFERENCES SOCIOS(CODSOCIO);

ALTER TABLE ARTICULOS 
ADD CONSTRAINT FK_CODTIPO_TIPOS_ARTICULO_ARTICULOS
FOREIGN KEY (CODTIPO)
REFERENCES TIPOS_ARTICULO(CODTIPO);


ALTER TABLE PRESTAMOS 
ADD CONSTRAINT FK_CODARTICULO_ARTICULOS_PRESTAMOS
FOREIGN KEY (CODARTICULO)
REFERENCES ARTICULOS(CODARTICULO);

ALTER TABLE CD 
ADD CONSTRAINT FK_CODARTICULO_ARTICULOS_CD
FOREIGN KEY (CODARTICULO)
REFERENCES ARTICULOS (CODARTICULO);

ALTER TABLE LIBRO 
ADD CONSTRAINT FK_CODARTICULO_ARTICULOS_LIBRO
FOREIGN KEY (CODARTICULO)
REFERENCES ARTICULOS (CODARTICULO);

ALTER TABLE PELICULA 
ADD CONSTRAINT FK_CODARTICULO_ARTICULOS_PELICULA
FOREIGN KEY (CODARTICULO)
REFERENCES ARTICULOS (CODARTICULO);

ALTER TABLE REL_TIPOAUTOR_AUTORES
ADD CONSTRAINT FK_CODAUTOR_AUTORES_REL_TIPOAUTOR_AUTORES
FOREIGN KEY (CODAUTOR)
REFERENCES AUTORES(CODAUTOR);

ALTER TABLE REL_TIPOAUTOR_AUTORES
ADD CONSTRAINT FK_CODTIPOAUTOR_TIPOS_AUTOR_REL_TIPOAUTOR_AUTORES
FOREIGN KEY (CODTIPOAUTOR)
REFERENCES TIPOS_AUTOR(CODTIPOAUTOR);

ALTER TABLE REL_AUTORES_ARTICULOS
ADD CONSTRAINT FK_CODARTICULO_ARTICULOS_REL_AUTORES_ARTICULOS
FOREIGN KEY (CODARTICULO)
REFERENCES ARTICULOS(CODARTICULO);

ALTER TABLE REL_AUTORES_ARTICULOS
ADD CONSTRAINT FK_CODTIPOAUTOR_REL_AUTORES_ARTICULOS
FOREIGN KEY (CODTIPOAUTOR)
REFERENCES TIPOS_AUTOR(CODTIPOAUTOR);

ALTER TABLE REL_AUTORES_ARTICULOS
ADD CONSTRAINT FK_CODAUTOR_AUTORES_REL_AUTORES_ARTICULOS
FOREIGN KEY (CODAUTOR)
REFERENCES AUTORES(CODAUTOR);