DROP TABLE COLABORADOR_PROYECTO;
DROP TABLE ENTIDADES;
DROP TABLE PERSONAS;
DROP TABLE PAGOS;
DROP TABLE TIPOSPAGOS;
DROP TABLE COLABORADORES;
DROP TABLE PROYECTOS;
DROP TABLE CLIENTES;

CREATE TABLE CLIENTES (
    CIF CHAR(9) NOT NULL PRIMARY KEY,
    NOMBRECLIENTE VARCHAR2(100),
    TELEFONO NUMBER (4),
    DOMICILIO VARCHAR2(15)
);

CREATE TABLE PROYECTOS (
    CODPROYECTO NUMBER(4) PRIMARY KEY NOT NULL,
    FECHACOMIENZO DATE,
    FECHA_DE_FIN DATE,
    CUANTIA NUMBER(10,2),
    FECHACONTRATO DATE,
    CIF CHAR(9)
);




CREATE TABLE COLABORADORES(
   NIF CHAR(9) PRIMARY KEY NOT NULL,
   NOMBRECOLABORADOR VARCHAR2(60),
   DOMICILIO VARCHAR2(100),
   TELEFONO NUMBER(9),
   RETENCION NUMBER(9),
   BANCO VARCHAR2(100),
   IBAN VARCHAR2(24),
   TIPOCOLABORADOR VARCHAR2(1)
);

CREATE TABLE TIPOSPAGOS (
    CODTIPO NUMBER(10) NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR2(30)
);


CREATE TABLE PAGOS(
    CODPAGO NUMBER(10) NOT NULL PRIMARY KEY,
    NIF CHAR(9),
    CONCEPTO VARCHAR2(60),
    CANTIDAD NUMBER(10,2),
    IVA NUMBER(10,2),
    FECHAPAGO DATE,
    CODTIPO NUMBER(10)
);

CREATE TABLE PERSONAS(
    NIF CHAR(9) PRIMARY KEY, 
    FECHANACIMIENTO DATE
);

CREATE TABLE ENTIDADES (
    NIF CHAR(9) PRIMARY KEY NOT NULL,
    FECHACONSTITUCION DATE,
    NUMEROEMPLEADOS NUMBER 
);


CREATE TABLE COLABORADOR_PROYECTO (
    CODPROYECTO NUMBER(4),
    NIF CHAR(9)
);


/*ALTER TABLE*/

ALTER TABLE PROYECTOS
ADD CONSTRAINT FK_CIF_CLIENTE
FOREIGN KEY (CIF)
REFERENCES CLIENTES(CIF);

ALTER TABLE COLABORADOR_PROYECTO 
ADD CONSTRAINT FK_CODPROYECTO_PROYECTOS
FOREIGN KEY (CODPROYECTO)
REFERENCES PROYECTOS(CODPROYECTO);


ALTER TABLE COLABORADOR_PROYECTO 
ADD CONSTRAINT FK_NIF_COLABORADORES
FOREIGN KEY (NIF)
REFERENCES COLABORADORES(NIF);



ALTER TABLE ENTIDADES
ADD CONSTRAINT FK_NIF_ENTIDADES_COLABORADORES
FOREIGN KEY (NIF)
REFERENCES COLABORADORES(NIF);



ALTER TABLE PERSONAS 
ADD CONSTRAINT FK_NIF_COLABORADORES_PERSONAS
FOREIGN KEY (NIF)
REFERENCES COLABORADORES(NIF);


ALTER TABLE PAGOS
ADD CONSTRAINT FK_NIF_PAGOS_COLABORADORES
FOREIGN KEY (NIF)
REFERENCES COLABORADORES(NIF);


ALTER TABLE PAGOS 
ADD CONSTRAINT FK_CODTIPO_PAGOS_TIPOSPAGO
FOREIGN KEY (CODTIPO)
REFERENCES TIPOSPAGOS(CODTIPO);

