CREATE TABLE GUERRA (
    COD_GRR INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(10),
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);

CREATE TABLE PARTICIPA (
    FK_COD_GRR INTEGER,
    FK_COD_PAIS INTEGER,
    COD_GRR INTEGER,
    COD_PAIS INTEGER  
);

DROP TABLE PARTICIPA;

ALTER TABLE PARTICIPA 
ADD CONSTRAINT FK_COD_GRR_GUERRA 
FOREIGN KEY (COD_GRR)
REFERENCES GUERRA (COD_GRR);

ALTER TABLE PARTICIPA
ADD CONSTRAINT FK_COD_PAIS
FOREIGN KEY (COD_PAIS)
REFERENCES PAISES (COD_PAIS);

CREATE TABLE PAISES (
    COD_PAIS INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(10)
    );

DROP TABLE PERIODO_INDEPENDECIA;

CREATE TABLE PERIODO_INDEPENDECIA (
    COD_PER_IND INTEGER NOT NULL PRIMARY KEY,
    FK_COD_PAIS INTEGER,
    ANIO_DEPENDIENCIA INTEGER
);


ALTER TABLE PERIODO_INDEPENDECIA
ADD CONSTRAINT FK_COD_PAIS_PAISES 
FOREIGN KEY (FK_COD_PAIS)
REFERENCES PAISES (COD_PAIS);
