CREATE TABLE SOCIO (
    COD_SOCIO INTEGER NOT NULL PRIMARY KEY, 
    NOMBRE VARCHAR2(10),
    APELLIDO VARCHAR2(10),
    DNI VARCHAR2(12),
    DIRECCION VARCHAR2(10),
    TLF VARCHAR2(12)
);

CREATE TABLE PRESTAMO (
    COD_PRESTAMO INTEGER NOT NULL PRIMARY KEY, 
    FK_COD_SOCIO INTEGER REFERENCES SOCIO(COD_SOCIO),
    FECHA_PRESTAMO DATE, 
    FECHA_TOPE_DEVOLUCION DATE,
    FECHA_DEVOLUCION DATE
);

CREATE TABLE LIBRO (
    COD_ARTICULO INTEGER NOT NULL PRIMARY KEY,
    FK_COD_PRESTAMO INTEGER REFERENCES PRESTAMO(COD_PRESTAMO), 
    ESTADO_ARTICULO VARCHAR2(10),
    COMENTARIO_ESTADO VARCHAR2(30), 
    NUM_PAGINAS INTEGER,
    PAIS VARCHAR2(10),
    RESUMEN_OBRA VARCHAR2(30),
    ANIO INTEGER,
    OBRA VARCHAR2(15)
);

CREATE TABLE ESCRIBE (
    FK_COD_ARTICULO_LIBRO INTEGER REFERENCES LIBRO(COD_ARTICULO),
    FK_COD_AUTOR REFERENCES AUTOR(COD_AUTOR)
);

CREATE TABLE AUTOR (
    COD_AUTOR INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(10),
    APELLIDO VARCHAR2(10)
);

CREATE TABLE PELICULA (
    COD_ARTICULO INTEGER NOT NULL PRIMARY KEY,
    FK_COD_PRESTAMO INTEGER REFERENCES PRESTAMO(COD_PRESTAMO), 
    ESTADO_ARTICULO VARCHAR2(10),
    COMENTARIO_ESTADO VARCHAR2(30), 
    DURACION INTEGER,
    PAIS VARCHAR2(10),
    DIRECTOR VARCHAR2(30),
    ANIO INTEGER,
    OBRA VARCHAR2(15)
);

CREATE TABLE CD (
    COD_ARTICULO INTEGER NOT NULL PRIMARY KEY,
    FK_COD_PRESTAMO INTEGER REFERENCES PRESTAMO(COD_PRESTAMO), 
    ESTADO_ARTICULO VARCHAR2(10),
    COMENTARIO_ESTADO VARCHAR2(30), 
    NUM_CANCIONES INTEGER,
    PAIS VARCHAR2(10),
    DIRECTOR VARCHAR2(30),
    ANIO INTEGER,
    OBRA VARCHAR2(15)
);