CREATE TABLE DEPARTAMENTOS(
    COD_DEPARTAMENTO VARCHAR2(10) NOT NULL PRIMARY KEY, 
    NOM_DEPARTAMENTO VARCHAR2(20)
);



CREATE TABLE COORDINADOR_DEPARTAMENTO (
    PK_COD_RESPONSABLE_COORDINADOR_DEPARTAMENTO  
    VARCHAR2(10) NOT NULL PRIMARY KEY,
    FK_COD_DEPARTAMENTO VARCHAR2(10) REFERENCES 
    DEPARTAMENTOS(COD_DEPARTAMENTO)
);

CREATE TABLE EMPLEADOS (
    PK_COD_TRABAJADOR VARCHAR2(10) NOT NULL PRIMARY KEY,
    FK_COD_RESPONSABLE_COORDINADOR_DEPARTAMENTO  VARCHAR2(10) 
    REFERENCES 
    COORDINADOR_DEPARTAMENTO (PK_COD_RESPONSABLE_COORDINADOR_DEPARTAMENTO),
    NUM_SS VARCHAR2(20),
    DNI CHAR(9), 
    NOMBRE_TRAB VARCHAR2(20),
    APELLIDOS_TRAB VARCHAR2(30),
    DIRECCION VARCHAR2(100),
    TELEFONO CHAR(12)

);

CREATE TABLE CATEGORIAS (
    PK_COD_CATEGORIA VARCHAR2(10) NOT NULL PRIMARY KEY, 
    NOM_CATEGORIA VARCHAR2(20)
);

CREATE TABLE CONTRATOS (
    PK_COD_CONTRATO VARCHAR2(10) NOT NULL PRIMARY KEY, 
    FK_COD_CATEGORIA VARCHAR2(10) REFERENCES 
    CATEGORIAS(PK_COD_CATEGORIA),
    FECHA_INICIO DATE,
    FECHA_FINAL DATE

);

CREATE TABLE NOMINAS (
    COD_NOMINA VARCHAR2(10) NOT NULL PRIMARY KEY, 
    FK_COD_CONTRATO VARCHAR2(10) REFERENCES CONTRATOS (PK_COD_CONTRATO),
    FECHA_NOM DATE,
    SALARIO INTEGER 
);




