CREATE TABLE JUGADOR (
    COD_JUGADOR INTEGER PRIMARY KEY NOT NULL,
    FK_COD_EQUIPO_FUTBOL INTEGER REFERENCES EQUIPOS_FUTBOL(COD_EQUIPO_FUTBOL),
    NOMBRE VARCHAR2(10),
    EDAD INTEGER, 
    DORSAL INTEGER
);


CREATE TABLE EQUIPOS_FUTBOL (
    COD_EQUIPO_FUTBOL INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(10),
    NOMBRE_PRESIDENTE VARCHAR2(10),
    NUM_AFILIADO INTEGER,
    ANIO_CREACION INTEGER
);

CREATE TABLE ESTADIO (
    COD_ESTADIO INTEGER NOT NULL PRIMARY KEY,
    FK_COD_TIPOLOGIA INTEGER REFERENCES TIPOLOGIA_ESTADIO (COD_TIPOLOGIA),
    NOMBRE VARCHAR2(10),
    CAPACIDAD INTEGER,
    TIPOLOGIA INTEGER
);

CREATE TABLE ARBITRO (
    COD_ARBITRO INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(10),
    FECHA_NACIMIENTO DATE,
    TIPO_ARBITRO VARCHAR2(10)
);

CREATE TABLE PARTIDO (
    COD_PARTIDO INTEGER PRIMARY KEY NOT NULL,
    FK_COD_ESTADIO INTEGER REFERENCES ESTADIO(COD_ESTADIO),
    FK_COD_EQUIPO_FUTBOL INTEGER REFERENCES EQUIPOS_FUTBOL (COD_EQUIPO_FUTBOL),
    FK_COD_ARBITRO INTEGER REFERENCES ARBITRO(COD_ARBITRO),
    JUGADOR_BANQUILLO VARCHAR2(10),
    JUGADOR_TITULAR VARCHAR2(10)
);

CREATE TABLE DETALLE_PARTIDO(
    COD_DETALLE_PARTIDO INTEGER NOT NULL PRIMARY KEY,
    FK_COD_PARTIDO INTEGER REFERENCES PARTIDO(COD_PARTIDO),
    DETALLE_GOL VARCHAR2(30),
    TIPO_TARJETA VARCHAR2(10),
    MINUTO_TARJETA VARCHAR2(10),
    MINUTO_GOL VARCHAR2(10)
);

CREATE TABLE INCIDENCIAS (
    COD_INCIDENCIA INTEGER,
    FK_COD_PARTIDO INTEGER REFERENCES PARTIDO(COD_PARTIDO),
    GRAVEDAD VARCHAR2(30),
    NOMBRE_JUGADOR VARCHAR2(10),
    TIPO_INCIDENCIA VARCHAR2(30),
    TIPO_LESION VARCHAR2(30)
);

CREATE TABLE TIPOLOGIA_ESTADIO (
    COD_TIPOLOGIA INTEGER NOT NULL PRIMARY KEY,
    TIPOLOGIA VARCHAR2(10)
);