DROP TABLE NOMINAS;
DROP TABLE CONTRATOS;
DROP TABLE CATEGORIAS;
DROP TABLE COORDINADORES_DEPARTAMENTOS;
DROP TABLE EMPLEADOS;
DROP TABLE DEPARTAMENTO;

CREATE TABLE DEPARTAMENTO (
    COD_DEPARTAMENTO VARCHAR2(10) NOT NULL PRIMARY KEY,
    NOM_DEPARTAMENTO VARCHAR2(20)
);

CREATE TABLE EMPLEADOS (
    COD_TRABAJADOR VARCHAR2(10) NOT NULL PRIMARY KEY, 
    COD_DEPARTAMENTO VARCHAR2(10),
    COD_RESPONSABLE VARCHAR2(10),
    NUM_SS VARCHAR2(20),
    DNI CHAR(9),
    NOMBRE_TRAB VARCHAR2(20),
    APELLIDOS_TRAB VARCHAR2(30),
    DIRECCION VARCHAR2(100),
    TELEFONO CHAR(12)
);

CREATE TABLE COORDINADORES_DEPARTAMENTOS (
    COD_DEPARTAMENTO VARCHAR2(10),
    COD_TRABAJADOR VARCHAR2(10) 
);

CREATE TABLE CATEGORIAS (
    COD_CATEGORIA VARCHAR2(10) PRIMARY KEY,
    NOM_CATEGORIA VARCHAR2(20)
);



CREATE TABLE CONTRATOS (
    COD_CONTRATO VARCHAR2(10) NOT NULL PRIMARY KEY,
    COD_CATEGORIA VARCHAR2(10),
    COD_TRABAJADOR  VARCHAR2(10),
    FECHA_INICIO DATE,
    FECHA_FINAL DATE
);

CREATE TABLE NOMINAS (
    COD_NOMINA VARCHAR2(10) NOT NULL PRIMARY KEY,
    COD_CONTRATO VARCHAR2(10),
    FECHA_NOM DATE,
    SALARIO INTEGER
);


/*-
/*ALTER TABLE */
ALTER TABLE EMPLEADOS 
ADD CONSTRAINT FK_COD_DEPARTAMENTO_DEPARTAMENTO 
FOREIGN KEY (COD_DEPARTAMENTO)
REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO);

ALTER TABLE COORDINADORES_DEPARTAMENTOS 
ADD CONSTRAINT FK_COD_TRABAJADOR_EMPLEADOS 
FOREIGN KEY (COD_TRABAJADOR)
REFERENCES EMPLEADOS(COD_TRABAJADOR);

ALTER TABLE COORDINADORES_DEPARTAMENTOS 
ADD CONSTRAINT FK_COD_DEPARTAMENTO
FOREIGN KEY (COD_DEPARTAMENTO)
REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO);

ALTER TABLE CONTRATOS
ADD CONSTRAINT COD_TRABAJADOR_EMPLEADOS 
FOREIGN KEY (COD_TRABAJADOR)
REFERENCES EMPLEADOS(COD_TRABAJADOR);

ALTER TABLE CONTRATOS
ADD CONSTRAINT COD_CATEGORIA_CATEGORIAS 
FOREIGN KEY (COD_CATEGORIA) 
REFERENCES CATEGORIAS(COD_CATEGORIA);

ALTER TABLE NOMINAS
ADD CONSTRAINT FK_COD_CONTRATO_NOMINAS 
FOREIGN KEY(COD_CONTRATO)
REFERENCES CONTRATOS(COD_CONTRATO);

