SELECT *
FROM EMP
WHERE EMP.SAL >=1000;

SELECT *
FROM EMP;

SELECT * 
FROM DEPT;

SELECT EMP.SAL, SAL
FROM DEPT, EMP
WHERE DEPT.DEPTNO = EMP.DEPTNO;


SELECT E.SAL--E.JOB------------------------
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
AND e.sal>= 1000;


SELECT *
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO;

/*********************************************************/
/*** REGLA GENERAL PARA LAS QUERIES*******
1. EXISTE ALGUN PRECALCULO-- UTILIZO SUBCONSULTAS
2. ME ENCUENTRO EN LA SUBCONSULTA. EXISTE ALGUN PRECALCULO--VUELVO AL PUNTO UNO
3. DONDE ESTA LA INFORMACIÓN-- ESTO LO PONGO EN EL FROM
4. QUE INFORMACION QUIERO MOSTRAR.
5. EXISTE ALGUNA FUNCION DE AGREGACION-- SI ES ASI, TODO LO QUE ESTA FUERA DE LA FUNCION DE 
   AGREGACIÓN VA AL GROUP BY
6. EXISTE ALGUNA CONDICION SOBRE LAS COLUMNAS DE LAS TABLAS--ESTO VA AL WHERE   
7. EXISTE ALGUNA CONDICION SOBRE LAS FUNCIONES DE AGREGACION-- ESTO VA AL HAVING   
8. EXISTE ALGUNA ORDENACION-- ESTO VA EN EL ORDER BY.
*******/


--OBTENER LOS EMPLEADOS QUE TIENEN EL MISMO TRABAJO QUE FORD.
V_TRABAJO_FORD
SELECT UPPER(JOB) FROM EMP WHERE UPPER(ENAME) = 'FORD';

SELECT *
FROM EMP E
WHERE UPPER(E.JOB) = (SELECT UPPER(JOB) FROM EMP WHERE UPPER(ENAME) = 'FORD');

-- OBTENER LOS EMPLEADOS QUE TIENEN EL MISMO TRABAJO QUE 
-- AQUELLOS QUE TRABAJAN EN CHICAGO SIN INCLUIR A LA GENTE DE CHICAGO.
V_TRABAJOS__DE_CHICAGO

-- EL DISTINCT VALE PARA QUE LA TERNO O COLUMNA NO SAQUE VALORES REPETIDOS
SELECT  DISTINCT JOB, SAL
FROM EMP;

--
SELECT DISTINCT UPPER(E.JOB)
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
AND UPPER(D.LOC) = 'CHICAGO';


SELECT *
FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO
AND UPPER(D.LOC) <> 'CHICAGO'
AND UPPER(E.JOB) IN (SELECT DISTINCT UPPER(E.JOB)
                    FROM DEPT D, EMP E
                    WHERE D.DEPTNO = E.DEPTNO
                    AND UPPER(D.LOC) = 'CHICAGO'
                    );

-- OBTENER UN LISTADO DE NOMBRE DE DEPARTAMENTO Y NOMBRE DE EMPLEADOS ORDENADOS DE MAYOR A MENOR SUELDO 
-- APARECIENDO EL FORMATO
--  ACCOUNTING KING 5000$
--  SALES JONES 2950$


SELECT D.DNAME, E.ENAME, E.SAL||'$',TO_CHAR(E.SAL,'9,999,999$') 
FROM DEPT D, EMP E WHERE D.DEPTNO = E.DEPTNO ORDER BY E.SAL DESC; 

-- OBTENER LOS NOMBRES DE LOS DEPARTAMENTOS ORDENADOS ALFABETICAMENTE DESCENDENTEMENTE QUE CONTIENEN LA LETRA E -- Y QUE SE GASTAN EN SUELDO MÁS DE 10000 EUROS 
SELECT D.DNAME,SUM(E.SAL) FROM DEPT D, EMP E WHERE D.DEPTNO = E.DEPTNO AND UPPER(D.DNAME) LIKE '%E%' GROUP BY D.DNAME HAVING SUM(E.SAL) >= 10000 ORDER BY D.DNAME DESC; 

-- OBTENER LOS NOMBRES DE LOS DEPARTAMENTOS ORDENADOS ALFABETICAMENTE DESCENDENTEMENTE QUE CONTIENEN LA LETRA E -- Y QUE SE GASTAN EN SUELDO MÁS DE 10000 EUROS, TENIENDO EN CUENTA LA COMISION