/*
SI POR CADA TRIENIO LE SUBEN 10 EUROS, CUANTO COBRA AL DIA DE HOY
CADA EMPLEADO. MOSTRAR EL NOMBRE, EL SUELDO ANTIGUO Y EL SUELDO CON 
TRIENIOS
*/

/*
SE CALCULA EL TOTAL DE MESES QUE HAY ENTRE LA FECHA DE CONTRATACION
Y LA FECHA ACTUAL PARA SABER EL TOTAL DE MESES TRANSCURRIDO CON EL 
USO DE MONTHS_BETWEEN(FECHA ACTUAL Y HIREDATE)

CALCULAR APARTE LA CANTIDAD DE TRIENIO. EN ESTE CASO ES UNO QUE 
ES IGUAL A 12+12+12 PORQUE EL TRIENIO TIENE 12 MESES CADA UNO

CALCULAR LA CANTIDAD DE MESES TRANSCURRIDOS / 36 (DEL RESULTADO ANTERIOR)

MULTIPLICAR EL RESULTADO DE LOS MESES TRANSCURRIDO DIVIDIDO 36 POR
10 (QUE ES CUÁNTO TE HAN SUBIDO) 
                                            ^
SUMAR EL SUELDO ANTIGUO MAS EL INCREMENTO (RESULTADO ANTERIOR) 

*/

SELECT ENAME, SAL,
ROUND(SAL + (TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE))) / 36 * 10,2)
AS TOTAL_DE_MESES_TRANSCURRIDO
FROM EMP;




