/*SELECT NOMBREDECOLUMNA O COLUMNAS O *
FROM TABLA
WHERE CONDICIONES
ORDER BY COLUMNAS;
*/

SELECT *
FROM ALUMNOS
WHERE SEXO = 'M'
AND EDAD >=19
AND FECNAC >= TO_DATE('01/15/2000','MM/DD/YYYY');

--AND FECNAC >= TO_DATE('01/03/2000','DD/MM/YYYY');


SELECT TO_DATE('01/15/2022','MM/DD/YYYY') FROM DUAL;


SELECT * FROM ALUMNOS
ORDER BY NOMBRE;

SELECT * FROM ALUMNOS
ORDER BY NOMBRE DESC;

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') FROM DUAL;

SELECT NOMBRE, EDAD, EDAD -33, FECNAC, FECNAC +1, SYSDATE - FECNAC 
AS DIAS_VIVIDOS, NOMBRE ||' '|| APELLIDOS AS NOMBRE_COMPLETO
FROM ALUMNOS
WHERE SEXO ='H';



-- 1-- EXISTE ALGUN CALCULO PREVIO NECESARIO
-- 2-- DONDE ESTA LA INFORMACION
-- 3-- QUE INFORMACIÓN NECESITO
-- 4-- EXISTE ALGUNA RESTRICCIÓN SOBRE LA INFORMACIÓN.


-- OBTENER EL NOMBRE COMPLETO DE LOS ALUMNOS QUE NACIERON EN EL AÑO 2000
SELECT NOMBRE ||' '|| APELLIDOS AS NOMBRE_COMPLETO, FECNAC
FROM ALUMNOS
WHERE FECNAC >= TO_DATE('01/01/2000','DD/MM/YYYY')
AND TO_DATE('01/01/2000','DD/MM/YYYY') > FECNAC  ;
--AND FECNAC < TO_DATE('01/01/2000','DD/MM/YYYY');

-- EL NOMBRE Y LA FECNAC DE LOS QUE CUMPLE 22 EL AÑO QUE VIENE
SELECT NOMBRE, FECNAC
FROM ALUMNOS
WHERE EDAD +1 = 22;