/*
INSERT INTO ESTADIOS (CODESTADIO,NOMBRE,CAPACIDAD,CIUDAD,CODEQUIPO) 
VALUES (1,'Estadio Santiago Bernabéu',81044,'Madrid'
,(SELECT CODEQUIPO FROM EQUIPOS WHERE UPPER(NOMBRE) = UPPER('Real Madrid CF')));
*/

DESCRIBE ESTADIOS;

SELECT * 
FROM ESTADIOS;

DELETE FROM ESTADIOS;

/*

*/

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(1, 'SANTIAGO BERNABEU',TO_CHAR(81.044, '99,999'), 'MADRID', 1);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(2, 'SPOTIFY CAMP NOU',TO_CHAR(99.354, '99,999'), 'BARCELONA', 2);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(3, 'CIVITAS METROPOLITANO',TO_CHAR(19.55, '99,99'), 'MADRID', 3);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(4, 'REALE ARENA',TO_CHAR(39.313), 'SAN SEBASTIAN', 4 );


INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(5, 'LA CERAMICA',TO_CHAR(23.500), 'VILLARREAL', 5);


INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(6, 'BENITO VILLAMARIN',TO_CHAR(59.378), 'SEVILLA', 6);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(7, 'MESTALLA',TO_CHAR(48.600, '99,999'), 'VALENCIA', 7);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(8, 'RAMON SANCHEZ PIZJUAN',TO_CHAR(43.883), 'SEVILLA', 8);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(9, 'SAN MAMES',TO_CHAR(53.289), 'BILBAO', 9);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(10, 'COLISEUM ALFONSO PEREZ',TO_CHAR(16.800), 'MADRID', 10);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(11, 'EL SADAR',TO_CHAR(23.576), 'NAVARRA', 11);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(12, 'ABANCA BALAIDOS',TO_CHAR(29.000), 'VIGO', 12);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(13, 'MONTILIVI',TO_CHAR(13.286), 'GERONA', 13);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(14, 'CAMPO DE FUTBOL DE VALLECAS',TO_CHAR(15.105), 'MADRID', 14);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(15, 'RCDE STADIUME',TO_CHAR(40.500), 'BARCELONA', 15);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(16, 'POWER HORSE STADIUM',TO_CHAR(15.274), 'ALMERIA', 16);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(17, 'MALLORCA SON MOIX',TO_CHAR(20.500), 'MALLORCA', 17);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(18, 'NUEVO MIRANDILLA',TO_CHAR(40.500), 'CADIZ', 18);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(19, 'NUEVO JOSE ZORRILLA',TO_CHAR(27.618), 'VALLADOLID', 19);

INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(20, 'MANUEL MARTINEZ VALERO',TO_CHAR(31.388), 'VALENCIA', 20);

/*
INSERT INTO ESTADIOS(CODESTADIO, NOMBRE, CAPACIDAD, CIUDAD, CODEQUIPO)
VALUES(18, 'RCDE STADIUME',TO_CHAR(40.500), 'BARCELONA', 18);
*/
