SELECT *
FROM PARTIDOS;

DESCRIBE PARTIDOS;

DELETE FROM PARTIDOS;

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(1,'20/21', 7, 21, 4,2,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(2,'20/21', 7, 22, 1,1,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(3,'20/21', 7, 6, 0,2,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(4,'20/21', 7, 10, 2,2,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(5,'20/21', 7, 1, 4,1,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(6,'20/21', 7, 3, 0,1,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(7,'20/21', 7, 9, 2,2,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(8,'20/21', 7, 8, 0,1,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(9,'20/21', 7, 18, 1,1,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(10,'20/21', 7, 11, 1,1,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(11,'20/21', 7, 20, 1,0,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(12,'20/21', 7, 12, 2,0,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(13,'20/21', 7, 5, 2,1,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(14,'20/21', 7, 24, 2,1,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(15,'20/21', 7, 4, 2,2,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(16,'20/21', 7, 26, 1,1,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(17,'20/21', 7, 2, 2,3,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(18,'20/21', 7, 19, 3,0,7);

INSERT INTO PARTIDOS(CODPARTIDO, CODTEMPORADA, CODEQUIPO_LOCAL, CODEQUIPO_VISITANTE, 
GOLES_EQUIPO_LOCAL , GOLES_EQUIPO_VISITANTE, CODESTADIO)
VALUES(19,'20/21', 7, 25, 4,1,7);


