SELECT *
FROM GOLEADORES;

DELETE FROM GOLEADORES;

DESCRIBE GOLEADORES;

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (1,1 ,5, 'HIZO GOL EN EL MINUTO 5' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (1,2 ,10, 'HIZO GOL EN EL MINUTO 10' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (1,3 ,12, 'HIZO GOL EN EL MINUTO 12' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (1,4 ,25, 'HIZO GOL EN EL MINUTO 25' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (2,2 ,4, 'HIZO GOL EN EL MINUTO 4' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (3,5 ,7, 'INTENTO FALLIDO' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (4,2 ,10, 'GOL MINUTO 10' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (4,10 ,50, 'GOL MINUTO 50' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (5,1 ,25, 'GOL MINUTO 25' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (5,3 ,35, 'GOL MINUTO 35' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (5,8 ,14, 'GOL MINUTO 14' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (5,11 ,45, 'GOL MINUTO 45' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (6,5 ,25, 'GOL FALLIDO' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (7,15 ,25, 'GOL MINUTO 25' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (7,18 ,35, 'GOL MINUTO 35' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (8,5 ,25, 'GOL FALLIDO MINUTO 25' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (9,10 ,25, 'GOL MINUTO 25' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (10,7 ,45, 'GOL MINUTO 45' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (11, 22,22, 'GOL MINUTO 22' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (12,24 ,3, 'GOL MINUTO 3' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (12,19 ,14, 'GOL MINUTO 14' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (13,24 ,3, 'GOL MINUTO 3' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (13,1 ,45, 'GOL MINUTO 45' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (14,4 ,7, 'GOL MINUTO 7' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (14,15 ,15, 'GOL MINUTO 15' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (15,15 ,15, 'GOL MINUTO 15' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (15,4 ,25, 'GOL MINUTO 25' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (16,9 ,40, 'GOL MINUTO 40' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (17,25 ,29, 'GOL MINUTO 29' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (17,24 ,32, 'GOL MINUTO 32' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (18,25 ,29, 'GOL MINUTO 29' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (18,24 ,28, 'GOL MINUTO 28' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (18,7 ,32, 'GOL MINUTO 32' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (19,25 ,29, 'GOL MINUTO 29' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (19,1 ,31, 'GOL MINUTO 31' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (19,25 ,34, 'GOL MINUTO 34' );

INSERT INTO GOLEADORES(CODPARTIDO,CODJUGADOR,MIN_GOL,OBSERVACION)
VALUES (19,1 ,40, 'GOL MINUTO 40' );

