SELECT *
FROM JUGADORES_EQUIPOS;

DESCRIBE JUGADORES_EQUIPOS;

DELETE FROM JUGADORES_EQUIPOS;

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='GIORGI MAMARDASHVILI'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='J. DOMENECH'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='L. HERRERIN'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='C. RIVERO'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='M. DIAKHANBY'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='GABRIEL PAULISTA'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='E. COMERT'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='C. OZKACAR'),7 );


INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE (NOMBRE)='C. Mosquera'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='J. GAYA'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='J. VAZQUEZ'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='TONY LATO'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='T. CORREIA'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='D. FOULQUIER'),7 );


INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='H. GUILLAMON'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='Y. MUSAH'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='N. GONZALEZ'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='A. ALMEIDA'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='L. MORIBA'),7 );


INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='S. LINO'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='J. KLUIVERT'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='S. CASTILLEJO'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='HUGO DURO'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='E. CAVANI'),7 );

INSERT INTO JUGADORES_EQUIPOS (CODTEMPORADA, CODJUGADOR,CODEQUIPO) 
VALUES ('20/21', (SELECT CODJUGADOR FROM JUGADORES WHERE UPPER(NOMBRE)='MARCOS ANDRE'),7 );

